export const expertises = [
  {
    id: "team-building",
    icon: "Mountain",
    title: "Team-Building",
    subtitle: "Sur terre, mer, air : tisser des liens forts",
    description:
      "Des challenges sportifs en montagne aux ateliers créatifs en ville, des régates en mer aux vols en montgolfière : nous créons des expériences de cohésion originales qui marquent durablement les esprits.",
    keywords: "team building original nature outdoor",
    image: "/images/koh-lanta-equilibre.png",
  },
  {
    id: "soirees-evenementielles",
    icon: "Sparkles",
    title: "Soirées Événementielles",
    subtitle: "Créer des soirées mémorables et élégantes",
    description:
      "Galas d'entreprise, soirées de fin d'année, soirées à thème : nous concevons des expériences sensorielles uniques. Décoration, artistique, restauration d'exception et animations sur mesure.",
    keywords: "organisation soirée gala entreprise sur mesure",
    image: "/images/masque-venitien.jpg",
  },
  {
    id: "seminaires-incentives",
    icon: "Users",
    title: "Séminaires",
    subtitle: "Fédérer vos équipes autour d'expériences sur mesure",
    description:
      "Du séminaire de direction au voyage incentive en passant par les activités de team-building : nous imaginons des moments forts qui renforcent l'engagement et la cohésion de vos collaborateurs. Sur mesure, de A à Z.",
    keywords: "organisation séminaire entreprise",
    image: "/images/koh-lanta-groupe.jpg",
  },
];

export const stats = [
  { value: 20, suffix: "+", label: "Années d'expérience" },
  { value: 500, suffix: "+", label: "Événements orchestrés" },
  { value: 120, suffix: "+", label: "Centres de congrès partenaires" },
  { value: 1, suffix: "", label: "Interlocuteur dédié par projet" },
];

export const testimonials = [
  {
    id: 1,
    quote:
      "Latitude a transformé notre séminaire en un moment d'exception. Leur professionnalisme et leur attention aux détails font toute la différence. Nous avons confié des événements à plusieurs agences — aucune n'a atteint ce niveau d'excellence.",
    author: "Claire Moreau",
    role: "Directrice des Ressources Humaines",
    company: "Groupe EDF",
    rating: 5,
  },
  {
    id: 2,
    quote:
      "Le rallye 2CV qu'ils ont organisé pour nos 200 commerciaux restera gravé dans les mémoires. Une logistique millimétrée, une ambiance folle, et une équipe qui anticipe chaque détail. On repart avec eux l'année prochaine.",
    author: "Sophie Lefranc",
    role: "Responsable Événements",
    company: "Renault Group",
    rating: 5,
  },
  {
    id: 3,
    quote:
      "Notre soirée de gala au Stade Français était tout simplement grandiose. Scénographie, traiteur, animations — tout était parfait. Latitude a su sublimer le lieu et créer une ambiance que nos collaborateurs n'ont pas près d'oublier.",
    author: "Thomas Garnier",
    role: "Directeur Général Adjoint",
    company: "BNP Paribas",
    rating: 5,
  },
  {
    id: 4,
    quote:
      "Du team-building Koh-Lanta en forêt à notre soirée de fin d'année à thème, Latitude a su comprendre notre culture d'entreprise et la retranscrire dans chaque événement. Partenaire de confiance depuis 5 ans.",
    author: "Marc Aubert",
    role: "Directeur Communication",
    company: "TotalEnergies",
    rating: 5,
  },
  {
    id: 5,
    quote:
      "Nous avons confié notre séminaire incentive à Marrakech à Latitude Organisation. Gestion visa, hébergement, programme sur mesure : zéro stress côté RH. Leurs équipes locales sont d'une fiabilité rare.",
    author: "Isabelle Durand",
    role: "DRH",
    company: "Capgemini France",
    rating: 5,
  },
  {
    id: 6,
    quote:
      "Le murder party qu'ils ont conçu pour notre team de direction était brillant. Scénario original, acteurs professionnels, mise en scène soignée. Un format bluffant qui a brisé tous les silos entre nos équipes.",
    author: "Alexandre Petit",
    role: "Directeur des Opérations",
    company: "AXA France",
    rating: 5,
  },
];

export const portfolio = [
  {
    id: 1,
    title: "Rallye des Impressionnistes",
    category: "Team-building",
    lieu: "Île-de-France",
    participants: 60,
    image: "/images/impressionnistes-satillieu.png",
    alt: "Séminaire créatif autour de la peinture impressionniste",
    size: "small",
  },
  {
    id: 2,
    title: "Soirée Vénitienne",
    category: "Soirées",
    lieu: "Paris",
    participants: 400,
    image: "/images/masque-venitien.jpg",
    alt: "Soirée gala à thème vénitien avec masques et décors somptueux",
    size: "small",
  },
  {
    id: 3,
    title: "Incentive Vercors",
    category: "Séminaires",
    lieu: "Vercors",
    participants: 200,
    image: "/images/rando-vercors.png",
    alt: "Randonnée incentive dans le Vercors avec vue panoramique",
    size: "medium",
  },
  {
    id: 4,
    title: "Les Aventuriers",
    category: "Team-building",
    lieu: "Île-de-France",
    participants: 80,
    image: "/images/koh-lanta-groupe.jpg",
    alt: "Team-building Les Aventuriers en plein air",
    size: "small",
  },
  {
    id: 5,
    title: "Grande Soirée Dansante",
    category: "Soirées",
    lieu: "Paris",
    participants: 500,
    image: "/images/animation-soiree-groupe.png",
    alt: "Soirée dansante d'entreprise pour 500 personnes",
    size: "large",
  },
  {
    id: 6,
    title: "Sens et Conscience",
    category: "Team-building",
    lieu: "Île-de-France",
    participants: 30,
    image: "/images/sens-conscience-bulle.png",
    alt: "Team-building Sens et Conscience expérience sensorielle",
    size: "small",
  },
  {
    id: 7,
    title: "Spéléologie",
    category: "Séminaires",
    lieu: "Ardèche",
    participants: 25,
    image: "/images/speleo.jpg",
    alt: "Incentive spéléologie groupe en grotte",
    size: "small",
  },
  {
    id: 8,
    title: "Soirée Casino",
    category: "Soirées",
    lieu: "Paris",
    participants: 150,
    image: "/images/casino-roulette.png",
    alt: "Animation casino roulette lors d'une soirée d'entreprise",
    size: "small",
  },
  {
    id: 9,
    title: "Canyoning",
    category: "Séminaires",
    lieu: "Alpes",
    participants: 40,
    image: "/images/canyoning.jpg",
    alt: "Incentive canyoning rappel en falaise",
    size: "small",
  },
  {
    id: 10,
    title: "Raids Gorges du Tarn",
    category: "Séminaires",
    lieu: "Ardèche",
    participants: 150,
    image: "/images/groupe-cascade.png",
    alt: "Raid incentive gorges du Tarn en pleine nature",
    size: "medium",
  },
  {
    id: 11,
    title: "Murder Party",
    category: "Team-building",
    lieu: "Paris",
    participants: 60,
    image: "/images/murder-atelier.jpg",
    alt: "Soirée murder party atelier enquête policière",
    size: "small",
  },
  {
    id: 12,
    title: "So British",
    category: "Team-building",
    lieu: "Île-de-France",
    participants: 45,
    image: "/images/so-british-croquet.png",
    alt: "Team-building So British croquet et activités anglaises",
    size: "small",
  },
  {
    id: 13,
    title: "Soirée Danone — Défense Arena",
    category: "Soirées",
    lieu: "Paris",
    participants: 1200,
    image: "/images/danone-arena.jpg",
    alt: "Soirée d'entreprise Danone à la Défense Arena",
    size: "large",
  },
  {
    id: 14,
    title: "Archéo Concept",
    category: "Team-building",
    lieu: "Rochefort",
    participants: 80,
    image: "/images/archeo-rochefort.jpg",
    alt: "Team-building Archéo Concept fouilles archéologiques",
    size: "medium",
  },
  {
    id: 15,
    title: "Medieval Fantasy",
    category: "Team-building",
    lieu: "Île-de-France",
    participants: 50,
    image: "/images/medieval-fantasy.jpg",
    alt: "Team-building Medieval Fantasy costumes et défis épiques",
    size: "small",
  },
  {
    id: 16,
    title: "Challenge à la Ferme",
    category: "Team-building",
    lieu: "Île-de-France",
    participants: 70,
    image: "/images/jeux-ferme.png",
    alt: "Team-building Challenge à la Ferme épreuves rurales",
    size: "small",
  },
  {
    id: 17,
    title: "Rallye 2CV",
    category: "Séminaires",
    lieu: "Île-de-France",
    participants: 60,
    image: "/images/rallye-2cv-new.jpg",
    alt: "Incentive rallye en Deux Chevaux découverte patrimoine",
    size: "small",
  },
  {
    id: 18,
    title: "Koh Lantable",
    category: "Team-building",
    lieu: "Île-de-France",
    participants: 90,
    image: "/images/koh-lantable-ambiance.png",
    alt: "Team-building Koh Lantable version indoor",
    size: "small",
  },
  {
    id: 20,
    title: "Soirée Peaky Blinders",
    category: "Soirées",
    lieu: "Paris",
    participants: 120,
    image: "/images/jerome-nabil-peaky.jpg",
    alt: "Soirée à thème Peaky Blinders ambiance années 20",
    size: "small",
  },
  {
    id: 21,
    title: "Biathlon",
    category: "Team-building",
    lieu: "Île-de-France",
    participants: 55,
    image: "/images/biathlon.jpg",
    alt: "Team-building biathlon tir laser et course en équipe",
    size: "small",
  },
  {
    id: 22,
    title: "Chasse au Trésor",
    category: "Team-building",
    lieu: "Île-de-France",
    participants: 60,
    image: "/images/archeo-bilboquet.jpg",
    alt: "Chasse au trésor team-building indices et énigmes",
    size: "small",
  },
  {
    id: 23,
    title: "Jeux du Vin",
    category: "Séminaires",
    lieu: "Île-de-France",
    participants: 30,
    image: "/images/degustation-soiree-ext.jpg",
    alt: "Jeux du vin dégustation oenologie team-building",
    size: "small",
  },
  {
    id: 24,
    title: "Challenge Temps X",
    category: "Team-building",
    lieu: "Île-de-France",
    participants: 50,
    image: "/images/buzzers-challenge.jpg",
    alt: "Challenge Temps X buzzers quiz compétition",
    size: "small",
  },
  {
    id: 25,
    title: "Magie",
    category: "Soirées",
    lieu: "Paris",
    participants: 100,
    image: "/images/presentateurs.jpg",
    alt: "Spectacle de magie animation soirée entreprise",
    size: "small",
  },
  {
    id: 26,
    title: "Au Théâtre Ce Soir",
    category: "Soirées",
    lieu: "Paris",
    participants: 80,
    image: "/images/jerome-police.jpg",
    alt: "Animation théâtrale soirée entreprise",
    size: "small",
  },
];

export const faqItems = [
  {
    question: "Quel est le délai idéal pour organiser un séminaire d'entreprise ?",
    answer:
      "Nous recommandons de nous contacter au minimum 3 mois avant la date souhaitée pour un séminaire standard, et 6 mois ou plus pour un événement de grande envergure (plus de 200 personnes) ou une destination internationale. Cela dit, nous sommes habitués à gérer des projets en urgence — n'hésitez pas à nous solliciter même avec des délais courts.",
  },
  {
    question: "Organisez-vous des événements à l'international ?",
    answer:
      "Oui, absolument. Titulaires de la Licence Agence de Voyage N°026-09-001, nous organisons des événements dans le monde entier. Nos destinations récurrentes incluent le Maroc, le Portugal, l'Espagne, l'Italie, la Suisse, la Turquie, l'Île Maurice, le Canada et les Caraïbes. Partout où vous souhaitez emmener vos équipes, nous avons le réseau et l'expertise pour le faire.",
  },
  {
    question: "Qu'est-ce qui différencie Latitude Organisation des autres agences événementielles ?",
    answer:
      "Deux choses nous distinguent fondamentalement. D'abord, l'interlocuteur unique : une seule personne vous accompagne du brief au bilan, garantissant cohérence et réactivité. Ensuite, notre réseau de 120+ centres partenaires en France, constitué depuis 20 ans, nous permet d'accéder à des lieux exclusifs aux meilleures conditions.",
  },
  {
    question: "Pouvez-vous gérer des événements de plus de 500 personnes ?",
    answer:
      "Oui, c'est notre quotidien. Nous avons organisé des congrès et conventions réunissant jusqu'à plusieurs milliers de participants. Notre expertise logistique, notre réseau de prestataires techniques et notre méthodologie éprouvée nous permettent de gérer des événements de toutes tailles avec la même attention aux détails.",
  },
  {
    question: "Proposez-vous des team-buildings originaux en pleine nature ?",
    answer:
      "C'est l'une de nos spécialités. Randonnées en montagne, régates en mer, survie en forêt, vols en montgolfière, rallyes 4x4 dans le désert marocain : nous créons des expériences outdoor qui sortent du cadre habituel et créent des souvenirs durables. Nous adaptons toujours l'activité à votre équipe, à ses capacités physiques et à vos objectifs de cohésion.",
  },
  {
    question: "Quelle est votre zone géographique d'intervention ?",
    answer:
      "Nous intervenons partout en France métropolitaine et dans les DOM-TOM, dans toute l'Europe et dans le monde entier. Notre réseau de 120+ centres de congrès couvre l'ensemble du territoire français, de Paris aux régions les plus reculées. Pour l'international, nous disposons d'un réseau de correspondants locaux de confiance dans une trentaine de pays.",
  },
];

export const destinations = [
  { name: "Paris", x: "47%", y: "32%", country: "France" },
  { name: "Lyon", x: "48%", y: "37%", country: "France" },
  { name: "Nice", x: "49%", y: "42%", country: "France" },
  { name: "Bordeaux", x: "44%", y: "40%", country: "France" },
  { name: "Chamonix", x: "50%", y: "39%", country: "France" },
  { name: "Marrakech", x: "44%", y: "52%", country: "Maroc" },
  { name: "Lisbonne", x: "40%", y: "44%", country: "Portugal" },
  { name: "Barcelone", x: "46%", y: "43%", country: "Espagne" },
  { name: "Rome", x: "51%", y: "43%", country: "Italie" },
  { name: "Genève", x: "50%", y: "37%", country: "Suisse" },
  { name: "Montréal", x: "22%", y: "32%", country: "Canada" },
  { name: "Île Maurice", x: "63%", y: "62%", country: "Île Maurice" },
];

export type PortfolioCategory = "Tous" | "Soirées" | "Team-building" | "Séminaires";
export const portfolioCategories: PortfolioCategory[] = ["Tous", "Soirées", "Team-building", "Séminaires"];
